bookApp/Components/CartViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using bookApp.Models;
using bookApp.Infrastructure;

namespace bookApp.Components {
    public class CartViewComponent : ViewComponent {

        public Cart cart { get; set; }
        public CartViewComponent(Cart c) { cart = c; }

        public IViewComponentResult Invoke() {
            cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            ViewBag.itemCount = cart.items.Count();
            return View(cart);
        }
    }
}

bookApp/Components/CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using bookApp.Models;

namespace bookApp.Components {
    public class CategoryViewComponent : ViewComponent {
        private IbookAppRepo repo { get; set; }
        public CategoryViewComponent(IbookAppRepo temp) { repo = temp; }

        public IViewComponentResult Invoke() {

            ViewBag.selectedCategory = RouteData?.Values["bookCategory"];

            var types = repo.books
                .Select(b => b.Category.CategoryName)
                .Distinct()
                .OrderBy(b => b);

            return View(types);
        }
    }
}

bookApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bookApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="~/favicon.jpg">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse w-100 order-1 dual-collapse2">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">bookApp</a>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" asp-route-bookCategory="" asp-route-pageNum="1">Home</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <vc:cart></vc:cart>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <vc:category></vc:category>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - bookApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

bookApp/Views/Shared/bookSummary.cshtml
@{}

@model Books

<br>
<div class="card" style="width: 30rem;">
    <div class="card-body">
        <h5 class="card-title">@Model.Title</h5>
        <h6 class="card-subtitle mb-2">@Model.Author</h6>
        <ul class="card-text list-group">
            <li class="list-group-item">Publisher: @Model.Publisher</li>
            <li class="list-group-item">Isbn: @Model.Isbn</li>
            <li class="list-group-item">Classification: @Model.Classification.ClassificationName</li>
            <li class="list-group-item">Category: @Model.Category.CategoryName</li>
            <li class="list-group-item">Pages: @Model.PageCount</li>
            <li class="list-group-item">Price: @Model.Price.ToString("c")</li>
        </ul>
    </div>
    <form method="post" asp-page="/Order">
        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnURL" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text">
            <button type="submit" class="btn btn-primary btn-sm">add to cart</button>
        </span>
    </form>
</div>