bookApp/Models/Order.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace bookApp.Models {
    public class Order {

        [Key]
        [BindNever]
        public int OrderId { get; set; }

        [BindNever]
        public ICollection<CartLineItem> lines { get; set; }

        [Required(ErrorMessage="Please enter a name:")]
        public string name { get; set; }

        [Required(ErrorMessage="Please enter at least 1 address line:")]
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }

        [Required(ErrorMessage="Please enter a city:")]
        public string city { get; set; }

        [Required(ErrorMessage="Please enter a state:")]
        public string state { get; set; }

        [Required(ErrorMessage="Please enter a zip code:")]
        public string zip { get; set; }
        public string country { get; set; }
    }
}

bookApp/Components/CartViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using bookApp.Models;
using bookApp.Infrastructure;

namespace bookApp.Components {
    public class CartViewComponent : ViewComponent {

        public Cart cart { get; set; }
        public CartViewComponent(Cart c) { cart = c; }

        public IViewComponentResult Invoke() {
            cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            ViewBag.itemCount = cart.items.Count();
            return View(cart);
        }
    }
}

bookApp/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using bookApp.Models;
using bookApp.Models.ViewModels;

namespace bookApp.Controllers {
    public class OrderController : Controller {

        private IorderRepo repo { get; set; }
        private Cart cart { get; set; }

        public OrderController(IorderRepo temp, Cart c) {
            repo = temp;
            cart = c;
        }

        [HttpGet]
        public IActionResult Checkout() { return View(new Order()); }

        [HttpPost]
        public IActionResult Checkout(Order order) {
            if (cart.items.Count() == 0) { ModelState.AddModelError("", "Your cart is empty!"); }
            if (ModelState.IsValid) {
                order.lines = cart.items.ToArray();
                repo.SaveOrder(order);
                cart.ClearCart();

                return RedirectToPage("/OrderConfirmation");
            }
            else { return View(); }
        }
    }
}

bookApp/Pages/Order.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using bookApp.Models;
using bookApp.Infrastructure;

namespace bookApp.Pages {
    public class OrderModel : PageModel {

        private IbookAppRepo repo { get; set; }
        public OrderModel(IbookAppRepo temp, Cart tCart) { repo = temp; cart = tCart; }
        public Cart cart { get; set; }
        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl) {
            ReturnUrl = returnUrl ?? "/";
            cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        public IActionResult OnPost(int bookID, string returnUrl) {

            Books book = repo.books.FirstOrDefault(b => b.BookId == bookID);
            cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            cart.AddItem(book, 1);

            HttpContext.Session.SetJson("cart", cart);
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookID, string returnUrl) {
            cart.RemoveItem(cart.items.First(x => x.book.BookId == bookID).book);
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

bookApp/Pages/Order.cshtml
@page
@model bookApp.Pages.OrderModel
@{
    ViewData["Title"] = "my cart"
}

<h3>your cart</h3>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>title</th>
            <th>quantity</th>
            <th>cost</th>
            <th>subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var b in Model.cart.items) {
            <tr>
                <td>@b.book.Title</td>
                <td>@b.quantity</td>
                <td>@(b.book.Price.ToString("c"))</td>
                <td>@((b.quantity * b.book.Price).ToString("c"))</td>
                <td class="text-center">
                    <form method="post" asp-page-handler="remove">
                        <input type="hidden" name="BookId" value="@b.book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button class="btn btn-primary btn-danger" type="submit">remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td>Cart Total:</td>
            <td colspan="3">@Model.cart.getTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>
<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">order more</a>
    <a class="btn btn-primary" asp-controller="Order" asp-action="Checkout">check out</a>
</div>

bookApp/Pages/OrderConfirmation.cshtml
@page
@model bookApp.Pages.OrderModel
@{}

<div class="text-center">
    <h3>thank you</h3>
    <br>
    <br>
    <p>Thanks for using bookApp!</p>
    <br>
    <a class="btn btn-primary" asp-controller="Home">return to home page</a>
    <br>
</div>

bookApp/Pages/_OrderLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bookApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="~/favicon.jpg">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse w-100 order-1 dual-collapse2">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">bookApp</a>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" asp-route-bookCategory="" asp-route-pageNum="1">Home</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <vc:cart></vc:cart>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - bookApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>